package com.intellidesk.ticket.entity;

import com.intellidesk.category.entity.Category;
import com.intellidesk.common.domain.BaseEntity;
import com.intellidesk.sla.entity.SlaPolicy;
import com.intellidesk.ticket.domain.TicketPriority;
import com.intellidesk.ticket.domain.TicketStatus;
import com.intellidesk.user.entity.User;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import java.time.Instant;

/**
 * The central aggregate of IntelliDesk.
 *
 * <p>Mapping decisions worth noting:</p>
 * <ul>
 *   <li>{@code ticketNumber} is a human-friendly business key (e.g. TKD-2026-000042)
 *       generated by the service layer; {@code id} stays the technical key.</li>
 *   <li>Associations are LAZY - REST responses are built from DTOs, so no entity
 *       graph leaks out and no circular JSON problem can occur.</li>
 *   <li>{@code slaPolicy} + {@code slaDeadlineAt}: the policy row is referenced for
 *       context, while the concrete deadline is frozen at creation time (audit-safe).</li>
 *   <li>{@code @Version} enables optimistic locking: two agents updating the same
 *       ticket concurrently produce a clear conflict instead of a silent overwrite.</li>
 * </ul>
 */
@Entity
@Table(
        name = "tickets",
        uniqueConstraints = @UniqueConstraint(name = "uk_tickets_ticket_number", columnNames = "ticket_number"),
        indexes = {
                @Index(name = "idx_tickets_reporter", columnList = "reporter_id"),
                @Index(name = "idx_tickets_agent", columnList = "assigned_agent_id"),
                @Index(name = "idx_tickets_status", columnList = "status"),
                @Index(name = "idx_tickets_priority", columnList = "priority"),
                @Index(name = "idx_tickets_category", columnList = "category_id"),
                @Index(name = "idx_tickets_sla_deadline", columnList = "sla_deadline_at")
        }
)
public class Ticket extends BaseEntity {

    @Column(name = "ticket_number", nullable = false, length = 20)
    private String ticketNumber;

    @Column(nullable = false, length = 150)
    private String title;

    @Column(nullable = false, columnDefinition = "text")
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private TicketStatus status = TicketStatus.OPEN;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private TicketPriority priority;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "reporter_id", nullable = false,
                foreignKey = @ForeignKey(name = "fk_tickets_reporter"))
    private User reporter;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assigned_agent_id",
                foreignKey = @ForeignKey(name = "fk_tickets_agent"))
    private User assignedAgent;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "category_id", nullable = false,
                foreignKey = @ForeignKey(name = "fk_tickets_category"))
    private Category category;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "sla_policy_id", nullable = false,
                foreignKey = @ForeignKey(name = "fk_tickets_sla_policy"))
    private SlaPolicy slaPolicy;

    @Column(name = "sla_deadline_at", nullable = false)
    private Instant slaDeadlineAt;

    @Column(name = "escalated_at")
    private Instant escalatedAt;

    @Column(name = "resolved_at")
    private Instant resolvedAt;

    @Column(name = "closed_at")
    private Instant closedAt;

    @Version
    @Column(nullable = false)
    private long version;

    protected Ticket() {
        // Required by JPA
    }

    public Ticket(String ticketNumber, String title, String description,
                  User reporter, Category category, TicketPriority priority,
                  SlaPolicy slaPolicy, Instant slaDeadlineAt) {
        this.ticketNumber = ticketNumber;
        this.title = title;
        this.description = description;
        this.reporter = reporter;
        this.category = category;
        this.priority = priority;
        this.slaPolicy = slaPolicy;
        this.slaDeadlineAt = slaDeadlineAt;
    }

    /**
     * The single mutation door for {@code status}: workflow services validate the
     * transition against {@link TicketStatus#canTransitionTo} and write an audit
     * record, then call this. There is deliberately no public setter.
     */
    public void changeStatus(TicketStatus newStatus) {
        this.status = newStatus;
    }

    public String getTicketNumber() {
        return ticketNumber;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public TicketStatus getStatus() {
        return status;
    }

    public TicketPriority getPriority() {
        return priority;
    }

    public void setPriority(TicketPriority priority) {
        this.priority = priority;
    }

    public User getReporter() {
        return reporter;
    }

    public User getAssignedAgent() {
        return assignedAgent;
    }

    public void setAssignedAgent(User assignedAgent) {
        this.assignedAgent = assignedAgent;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public SlaPolicy getSlaPolicy() {
        return slaPolicy;
    }

    public Instant getSlaDeadlineAt() {
        return slaDeadlineAt;
    }

    public void setSlaDeadlineAt(Instant slaDeadlineAt) {
        this.slaDeadlineAt = slaDeadlineAt;
    }

    public Instant getEscalatedAt() {
        return escalatedAt;
    }

    public void setEscalatedAt(Instant escalatedAt) {
        this.escalatedAt = escalatedAt;
    }

    public Instant getResolvedAt() {
        return resolvedAt;
    }

    public void setResolvedAt(Instant resolvedAt) {
        this.resolvedAt = resolvedAt;
    }

    public Instant getClosedAt() {
        return closedAt;
    }

    public void setClosedAt(Instant closedAt) {
        this.closedAt = closedAt;
    }

    public long getVersion() {
        return version;
    }
}
